"""create_celestial_table

Revision ID: 6ea917b7c6b9
Revises: 2369fdc08a40
Create Date: 2026-05-10 22:26:23.767938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ea917b7c6b9'
down_revision: Union[str, Sequence[str], None] = '2369fdc08a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celestial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.Column('sunset', sa.Time(), nullable=True),
    sa.Column('moonrise', sa.Time(), nullable=True),
    sa.Column('moonset', sa.Time(), nullable=True),
    sa.Column('moon_phase', sa.String(), nullable=True),
    sa.Column('moon_illumination', sa.Integer(), nullable=True),
    sa.Column('should_go_outside', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['weather_id'], ['weather.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
        INSERT INTO celestial_data (weather_id, sunrise, sunset, moonrise, moonset, moon_phase, moon_illumination, should_go_outside)
        SELECT id, sunrise, sunset, moonrise, moonset, moon_phase, moon_illumination, should_go_outside 
        FROM weather
    """)
               
    op.drop_column('weather', 'sunrise')
    op.drop_column('weather', 'should_go_outside')
    op.drop_column('weather', 'moon_illumination')
    op.drop_column('weather', 'moon_phase')
    op.drop_column('weather', 'moonset')
    op.drop_column('weather', 'sunset')
    op.drop_column('weather', 'moonrise')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('moonrise', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('sunset', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('moonset', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('moon_phase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('moon_illumination', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('should_go_outside', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('sunrise', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_table('celestial_data')
    # ### end Alembic commands ###
