"""Initial schema

Revision ID: 87a64cad3ef7
Revises: 
Create Date: 2026-05-08 13:21:49.660251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a64cad3ef7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('wind_degree', sa.Integer(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Enum('N', 'S', 'E', 'W', 'NW', 'NE', 'SW', 'SE', name='winddirection'), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.Column('sunset', sa.Time(), nullable=True),
    sa.Column('moonrise', sa.Time(), nullable=True),
    sa.Column('moonset', sa.Time(), nullable=True),
    sa.Column('moon_phase', sa.String(), nullable=True),
    sa.Column('moon_illumination', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
